# yaml-language-server: $schema=https://spec.openapis.org/oas/3.0/schema/2024-10-18
openapi: 3.0.0
info:
  title: Stellora Airline API
  version: 1.0.0
paths:
  /health:
    get:
      operationId: healthCheck
      summary: Health check endpoint
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
  /airports:
    get:
      operationId: listAirports
      summary: List all airports
      responses:
        '200':
          description: List of airports
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Airport'
    post:
      operationId: createAirport
      summary: Create a new airport
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                iataCode:
                  $ref: '#/components/schemas/AirportIATACode'
              required:
                - iataCode
      responses:
        '201':
          description: Airport created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Airport'
        '400':
          description: Invalid request
    delete:
      operationId: deleteAllAirports
      summary: Delete all airports
      responses:
        '204':
          description: All airports deleted
  /airports/{airportSpec}:
    get:
      operationId: getAirport
      summary: Get airport by ID or IATA code
      parameters:
        - $ref: '#/components/parameters/airportSpec'
      responses:
        '200':
          description: Airport found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Airport'
        '404':
          description: Airport not found
    patch:
      operationId: updateAirport
      summary: Update airport
      parameters:
        - $ref: '#/components/parameters/airportSpec'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                iataCode:
                  $ref: '#/components/schemas/AirportIATACode'                
      responses:
        '200':
          description: Airport updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Airport'
        '404':
          description: Airport not found
    delete:
      operationId: deleteAirport
      summary: Delete an airport
      parameters:
        - $ref: '#/components/parameters/airportSpec'
      responses:
        '204':
          description: Airport deleted
        '404':
          description: Airport not found
  /airports/{airportSpec}/flight-schedules:
    get:
      operationId: listFlightSchedulesByAirport
      summary: List flight schedules that depart from or arrive at an airport
      parameters:
        - $ref: '#/components/parameters/airportSpec'
      responses:
        '200':
          description: Flight schedules by airport
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FlightSchedule'
        '404':
          description: Airport not found
  /airlines:
    get:
      operationId: listAirlines
      summary: List all airlines
      responses:
        '200':
          description: List of airlines
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Airline'
    post:
      operationId: createAirline
      summary: Create a new airline
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                iataCode:
                  $ref: '#/components/schemas/AirlineIATACode'
                name:
                  type: string
              required:
                - iataCode
                - name
      responses:
        '201':
          description: Airline created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Airline'
        '400':
          description: Invalid request
    delete:
      operationId: deleteAllAirlines
      summary: Delete all airlines
      responses:
        '204':
          description: All airlines deleted
  /airlines/{airlineSpec}:
    get:
      operationId: getAirline
      summary: Get airline by ID or IATA code
      parameters:
        - $ref: '#/components/parameters/airlineSpec'
      responses:
        '200':
          description: Airline found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Airline'
        '404':
          description: Airline not found
    patch:
      operationId: updateAirline
      summary: Update airline
      parameters:
        - $ref: '#/components/parameters/airlineSpec'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                iataCode:
                  $ref: '#/components/schemas/AirlineIATACode'
                name:
                  type: string
      responses:
        '200':
          description: Airline updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Airline'
        '404':
          description: Airline not found
    delete:
      operationId: deleteAirline
      summary: Delete an airline
      parameters:
        - name: airlineSpec
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/AirlineSpec'
      responses:
        '204':
          description: Airline deleted
        '404':
          description: Airline not found
  /airlines/{airlineSpec}/flight-schedules:
    get:
      operationId: listFlightSchedulesByAirline
      summary: List flight schedules for an airline
      parameters:
        - $ref: '#/components/parameters/airlineSpec'
      responses:
        '200':
          description: Flight schedules by airline
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FlightSchedule'
        '404':
          description: Airline not found
  /flight-schedules:
    get:
      operationId: listFlightSchedules
      summary: List all flight schedules
      responses:
        '200':
          description: List of flight schedules
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FlightSchedule'
    post:
      operationId: createFlightSchedule
      summary: Create a new flight schedule
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                airline:
                  $ref: '#/components/schemas/AirlineSpec'
                number:
                  $ref: '#/components/schemas/FlightNumber'
                originAirport:
                  $ref: '#/components/schemas/AirportSpec'
                destinationAirport:
                  $ref: '#/components/schemas/AirportSpec'
                published:
                  type: boolean
                  default: false
              required:
                - airline
                - number
                - originAirport
                - destinationAirport
      responses:
        '201':
          description: Flight schedule created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightSchedule'
        '400':
          description: Invalid request
    delete:
      operationId: deleteAllFlightSchedules
      summary: Delete all flight schedules
      responses:
        '204':
          description: All flight schedules deleted
  /flight-schedules/{id}:
    get:
      operationId: getFlightSchedule
      summary: Get flight schedule by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Flight schedule found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightSchedule'
        '404':
          description: Flight schedule not found
    patch:
      operationId: updateFlightSchedule
      summary: Update flight schedule
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                airline:
                  $ref: '#/components/schemas/AirlineSpec'
                number:
                  $ref: '#/components/schemas/FlightNumber'
                originAirport:
                  $ref: '#/components/schemas/AirportSpec'
                destinationAirport:
                  $ref: '#/components/schemas/AirportSpec'
                published:
                  type: boolean
      responses:
        '200':
          description: Flight schedule updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightSchedule'
        '404':
          description: Flight schedule not found
    delete:
      operationId: deleteFlightSchedule
      summary: Delete a flight schedule
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Flight schedule deleted
        '404':
          description: Flight schedule not found
  /routes:
    get:
      operationId: listRoutes
      summary: List all routes
      responses:
        '200':
          description: List of routes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Route'
  /routes/{route}:
    get:
      operationId: getRoute
      summary: Get route by IATA codes of origin and destination airports
      parameters:
        - name: route
          in: path
          required: true
          schema:
            type: string
            pattern: '^[A-Z]{3}-[A-Z]{3}$'
      responses:
        '200':
          description: Route information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Route'
        '404':
          description: Route not found
components:
  parameters:
    airportSpec:
      name: airportSpec
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/AirportSpec'
    airlineSpec:
      name: airlineSpec
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/AirlineSpec'
  schemas:
    AirportID:
      type: integer
    AirportIATACode:
      type: string
      description: IATA code for airport
      pattern: '^[A-Z]{3}$'
      minLength: 3
      maxLength: 3
    AirportSpec:
      oneOf:
        - $ref: '#/components/schemas/AirportID'
        - $ref: '#/components/schemas/AirportIATACode'
    Airport:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        iataCode:
          $ref: '#/components/schemas/AirportIATACode'
        country:
          type: string
        region:
          type: string        
        point:
          $ref: '#/components/schemas/Point'
      required:
        - id
        - name
        - iataCode
        - country
        - region
        - point
    Point:
      type: object
      properties:
        longitude:
          type: number
          format: double
        latitude:
          type: number
          format: double
      required:
        - longitude
        - latitude
    AirlineID:
      type: integer
    AirlineIATACode:
      type: string
      description: IATA code for airline
      pattern: '^[A-Z]{2}$'
      minLength: 2
      maxLength: 2
    AirlineSpec:
      oneOf:
        - $ref: '#/components/schemas/AirlineID'
        - $ref: '#/components/schemas/AirlineIATACode'
    Airline:
      type: object
      properties:
        id:
          type: integer
        iataCode:
          $ref: '#/components/schemas/AirlineIATACode'
        name:
          type: string
      required:
        - id
        - iataCode
        - name
    FlightSchedule:
      type: object
      properties:
        id:
          type: integer
        airline:
          $ref: '#/components/schemas/Airline'
        number:
          $ref: '#/components/schemas/FlightNumber'
        originAirport:
          $ref: '#/components/schemas/Airport'
        destinationAirport:
          $ref: '#/components/schemas/Airport'
        distanceMiles:
          type: number
          format: double
        published:
          type: boolean
      required:
        - id
        - airline
        - number
        - originAirport
        - destinationAirport
        - published
    FlightNumber:
      type: string
      pattern: '^[0-9]{1,4}$'
    Route:
      type: object
      properties:
        originAirport:
          $ref: '#/components/schemas/Airport'
        destinationAirport:
          $ref: '#/components/schemas/Airport'
        distanceMiles:
          type: number
          format: double
        flightSchedulesCount:
          type: integer
      required:
        - originAirport
        - destinationAirport
        - flightSchedulesCount
      