# yaml-language-server: $schema=https://spec.openapis.org/oas/3.0/schema/2024-10-18
openapi: 3.0.0
info:
  title: Stellora Airline API
  version: 1.0.0
paths:
  /health:
    get:
      operationId: healthCheck
      summary: Health check endpoint
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
  /airports:
    get:
      operationId: listAirports
      summary: List all airports
      responses:
        '200':
          description: List of airports
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Airport'
    post:
      operationId: createAirport
      summary: Create a new airport
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                iataCode:
                  type: string
              required:
                - iataCode
      responses:
        '201':
          description: Airport created
        '400':
          description: Invalid request
    delete:
      operationId: deleteAllAirports
      summary: Delete all airports
      responses:
        '204':
          description: All airports deleted
  /airports/{id}:
    get:
      operationId: getAirport
      summary: Get airport by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Airport found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Airport'
        '404':
          description: Airport not found
    patch:
      operationId: updateAirport
      summary: Update airport
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                iataCode:
                  type: string                
      responses:
        '204':
          description: Flight updated
        '404':
          description: Flight not found
    delete:
      operationId: deleteAirport
      summary: Delete an airport
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Airport deleted
        '404':
          description: Airport not found
  /airports/{id}/flights:
    get:
      operationId: listFlightsByAirport
      summary: List flights that depart from or arrive at an airport
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Flights by airport
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flight'
  /flights:
    get:
      operationId: listFlights
      summary: List all flights
      responses:
        '200':
          description: List of flights
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flight'
    post:
      operationId: createFlight
      summary: Create a new flight
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                number:
                  type: string
                originAirport:
                  $ref: '#/components/schemas/airportSpec'
                destinationAirport:
                  $ref: '#/components/schemas/airportSpec'
                published:
                  type: boolean
                  default: false
              required:
                - number
                - originAirport
                - destinationAirport
      responses:
        '201':
          description: Flight created
        '400':
          description: Invalid request
    delete:
      operationId: deleteAllFlights
      summary: Delete all flights
      responses:
        '204':
          description: All flights deleted
  /flights/{id}:
    get:
      operationId: getFlight
      summary: Get flight by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Flight found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flight'
        '404':
          description: Flight not found
    patch:
      operationId: updateFlight
      summary: Update flight
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                number:
                  type: string
                originAirport:
                  type: integer
                destinationAirport:
                  type: integer
                published:
                  type: boolean
      responses:
        '204':
          description: Flight updated
        '404':
          description: Flight not found
    delete:
      operationId: deleteFlight
      summary: Delete a flight
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Flight deleted
        '404':
          description: Flight not found
components:
  schemas:
    airportSpec:
      title: AirportSpec
      oneOf:
        - type: integer
        - type: string
          pattern: '^[A-Z]{3}$'
          minLength: 3
          maxLength: 3
    Airport:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        iataCode:
          type: string
        point:
          $ref: '#/components/schemas/Point'
      required:
        - id
        - name
        - iataCode
        - point
    Point:
      type: object
      properties:
        longitude:
          type: number
          format: double
        latitude:
          type: number
          format: double
      required:
        - longitude
        - latitude
    Flight:
      type: object
      properties:
        id:
          type: integer
        number:
          type: string
        originAirport:
          $ref: '#/components/schemas/Airport'
        destinationAirport:
          $ref: '#/components/schemas/Airport'
        distanceMiles:
          type: number
          format: double
        published:
          type: boolean
      required:
        - id
        - number
        - originAirport
        - destinationAirport
        - distanceMiles
        - published