openapi: 3.0.0
info:
  title: Stellora Shop API
  version: 1.0.0
paths:
  /health:
    get:
      operationId: healthCheck
      summary: Health check endpoint
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
  /categories:
    get:
      operationId: listCategories
      summary: List all categories
      responses:
        '200':
          description: List of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    post:
      operationId: createCategory
      summary: Create a new category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
                - title
      responses:
        '201':
          description: Category created
        '400':
          description: Invalid request
  /categories/{id}:
    delete:
      operationId: deleteCategory
      summary: Delete a category
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Category deleted
        '404':
          description: Category not found

  /products:
    get:
      operationId: listProducts
      summary: List all products
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      operationId: createProduct
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
                - title
      responses:
        '201':
          description: Product created
        '400':
          description: Invalid request
    delete:
      operationId: deleteAllProducts
      summary: Delete all products
      responses:
        '204':
          description: All products deleted

  /products/{id}:
    get:
      operationId: getProduct
      summary: Get product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
    patch:
      operationId: setProductStarred
      summary: Set product starred status
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                starred:
                  type: boolean
              required:
                - starred
      responses:
        '204':
          description: Product updated
        '404':
          description: Product not found
    delete:
      operationId: deleteProduct
      summary: Delete a product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Product deleted
        '404':
          description: Product not found

  /categories/{categoryId}/products:
    get:
      operationId: listProductsByCategory
      summary: List products in a category
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Products categorization
          content:
            application/json:
              schema:
                type: object
                properties:
                  productsInCategory:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  productsNotInCategory:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                required:
                  - productsInCategory
                  - productsNotInCategory

  /products/{productId}/categories/{categoryId}:
    put:
      operationId: updateProductCategoryMembership
      summary: Set product category membership
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
        - name: categoryId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: boolean
              required:
                - value
      responses:
        '204':
          description: Membership updated
        '404':
          description: Product or category not found

components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
      required:
        - id
        - title

    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        starred:
          type: boolean
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
      required:
        - id
        - title
        - starred