name: ci

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
      - name: Set pnpm version from .tool-versions
        run: |
          PNPM_VERSION=$(grep pnpm .tool-versions | awk '{print $2}')
          npm pkg set packageManager="pnpm@${PNPM_VERSION}"
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
      - run: pnpm install
      - run: pnpm run build
